### ISSUE TITLE
Italian language not correct when I want to change the pin

### ISSUE THREAD

**Issue by herou** [soramitsu/fearless-Android#116]
In order to change the pin, I have to go through 3 steps:
1-Enter pin code
2-Enter new pin code
3-Confirm your pin code

If I change the language to Italian the text for each step is: 
1-Inserisci il codice PIN (Enter pin code)
2-Inserisci il codice PIN (Enter pin code)
3-Conferma il tuo codice Pin (Confirm your pin code)

In a few words, the text of the second step is the same as the text of the first step. The second step in the Italian language should be 
: Inserisci il nuovo codice PIN

I know the Italian language that's why :)

**Comment by ArtemNeFRiT** [comment]
fixed https://github.com/soramitsu/fearless-Android/pull/118/commits/1c5fd2b4afa5c457e61e3e245a17978d13793e73

**Comment by herou** [comment]
> fixed [1c5fd2b](https://github.com/soramitsu/fearless-Android/commit/1c5fd2b4afa5c457e61e3e245a17978d13793e73)

That's awesome
