### ISSUE TITLE
Add stubs for production secrets so everyone will be able to build the project

### ISSUE THREAD

**Issue by Lucifer6six** [soramitsu/fearless-Android#220]
in secrets.gradle file   ext.readSecret method 
because of  the secret param  in localProperties file is null  ,so content is null  in the content.startWith() method

**Comment by valentunn** [comment]
Hi, this is the correct behavior - we do not store secret keys in the public space, so you should add correspnding keys maunally to localProperties.
But i agree, that there should be some meaningfull error message so contributers can easily identify error
